### ISSUE TITLE
Review use of `https` with HSDS by dispatch-service

### ISSUE THREAD

**Issue by jonrkarr** [biosimulations/deployment#22]
I've needed to change the management of the configuration of HSDS because dev and prod were using the same server, passwords weren't securely set, the configuration used by the dispatch-service was hard coded into a file in the home directory of the HPC account, and there was no clear mechanism to distinguish the internal vs external base paths for the HSDS needed by the dispatch API (http://hsds:80) vs dispatch service (https://data.biosimulations.org). I'm not entirely sure where `http` vs `https` needs to be used. 

@bilalshaikh42 please review the use of `https` vs `http` below.

## dev
`config/dev/shared.env` (used by dispatch-service)
```
HSDS_EXTERNAL_BASEPATH=https://data.biosimulations.dev
```

`config/dev/hsds/config.yml`:
```
hsds_endpoint: https://data.biosimulations.dev # used for hateos links in response
```

## prod
`config/prod/shared.env` (used by dispatch-service)
```
HSDS_EXTERNAL_BASEPATH=https://data.biosimulations.org
```

`config/prod/hsds/config.yml`:
```
hsds_endpoint: https://data.biosimulations.org # used for hateos links in response
```

**Comment by bilalshaikh42** [comment]
Everything that points to the external url for the hsds should be https. (https://data.biosimularions.org) 

Using something like http://hsds:80 is happening internal to the kubernetes cluster, so that should be http since we don't have internal tls set up.

**Comment by jonrkarr** [comment]
Thanks. Previously there was a mixture, so I wasn't sure if http needed to be used somewhere due to lack of a certificate.

**Comment by bilalshaikh42** [comment]
I am confused by some of the changes 

The S3 url "http://s3low.scality...." can only be used behind the firewall, so setting the external storage url to that can cause problems. Not sure where this variable is being used

**Comment by jonrkarr** [comment]
The COMBINE API uses the S3 bucket for temporary storage. This has been that way for quite a while.

**Comment by bilalshaikh42** [comment]
My confusion is specifically with the commit here:
fb4ed9f1d6e846f8da18c986c3b5bad6d9d23ca3

I see that an additional "external" S3 url has been added, but it is the same as the regular one. 

I interpret external to mean urls that are being accessed outside of the firewall/ presented to users. 

Where is the added external S3 variable need to be used?

**Comment by jonrkarr** [comment]
Previously you had this hard coded this into the sbatch service. This was used to overrise the storage endpoint when `STORAGE_ENDPOINT=https://localhost:4443`.

**Comment by bilalshaikh42** [comment]
I see. That situation never arises except for local development, so I did not see a need to add a config for it. I suppose there is no reason not to
