### ISSUE TITLE
Purpose of tools-config

### ISSUE THREAD

**Issue by bilalshaikh42** [biosimulations/deployment#24]
What is the purpose of the tools-config? 
It does not seem to be mounted to any of the apps

**Comment by jonrkarr** [comment]
This is a place to store configuration for the owner of the example simulation runs so they are owned by the "BioSimulations Team" rather than any individual person. Its not intended to be attached to any applications.

**Comment by bilalshaikh42** [comment]
I am confused as it has been included in the customization file, loading it into the cluster. Are you intending just to store the secret for future use?

**Comment by bilalshaikh42** [comment]
This information is available in the auth0 dashboard, which seems to be the best place to look it up if needed. (Assuming that is the intention), since client secrets can be rotated.

**Comment by jonrkarr** [comment]
Yes it can be looked up at auth0, but one has to know which account to use. Its helpful to have a central place to store configuration. The secrets repository is the closest thing that has been created. Those secrets don't need to be available to the cluster, the repository is just a convenient place to organize them.

**Comment by bilalshaikh42** [comment]
I am still confused, as the various location contain the same information. Both prod and dev have the same client_id and client_secret. The audience is also the same, though that is deducible from the API that is being called.  Would it make more sense to just create a folder in the secrets repo that can contain any information that is needed?

**Comment by jonrkarr** [comment]
I separated the configuration from secrets and enabled the dev and prod examples to be owned by different accounts. Presently, the examples are set up to be owned by the same account. This could be removed from the kubernetes kustomization files.

**Comment by bilalshaikh42** [comment]
Removed from the cluster config
