### ISSUE TITLE
Remove old run.api.biosimulations deployments

### ISSUE THREAD

**Issue by jonrkarr** [biosimulations/deployment#29]

**Comment by bilalshaikh42** [comment]
These endpoints are likely still being used by the libretext project. As they are just an alias I propose just leaving them working

**Comment by jonrkarr** [comment]
We have many breaking changes. Any simulations they rely on won't be accessible anyway. They can be sent an email to ask them to switch.

**Comment by jonrkarr** [comment]
For them to be able to access old simulations, we'd have to maintain something more like v1.run.api.biosimulations.org. I don't see a compelling reason to do this.
