### ISSUE TITLE
Clean up `misc` directory

### ISSUE THREAD

**Issue by jonrkarr** [biosimulations/deployment#33]
This appears to define old resources such as `biosimulations-api` in `misc/resources.yml`

**Comment by bilalshaikh42** [comment]
This is largely a directory for old configs/references/experiments but I could certainly remove some of the older things in it. The old biosimulations-api mounts the NFS at unconn directly to the pod which was something that took a while to work out, so its stored there as a template

**Comment by jonrkarr** [comment]
It would always be in the history, granted not so easy to find. Can we rename it to something clearer like `scratch`?

**Comment by jonrkarr** [comment]
The name `misc` makes it sounds like it something that's actively used, even though its not.

**Comment by bilalshaikh42** [comment]
I added a note to the readme about the folder. We can rename it as well

**Comment by jonrkarr** [comment]
Sure
