### ISSUE TITLE
Review topology keys for affinity configuration for API

### ISSUE THREAD

**Issue by jonrkarr** [biosimulations/deployment#43]
I needed to make the `topologyKey` valid to enable deployments to proceed (see biosimulations/biosimulations#3872). 

@bilalshaikh42 please complete this part of the configuration.

https://github.com/biosimulations/deployment/blob/main/base/apps/api.yaml#L40

https://github.com/biosimulations/deployment/blob/main/base/apps/api.yaml#L51

**Comment by bilalshaikh42** [comment]
Sorry about that. The key you added in is correct. I forgot to include that.

**Comment by jonrkarr** [comment]
Closing because I set the configuration as intended.
